
projectName: &projectName test-pipeline

# used in the source step in the pipeline
projectSource:
  repoOwner: mjgoble
  repoName: test-pipeline
  repoBranch: main

# environment that the pipeline stack will live in
environment:
  account: '0123456789012'
  region: ap-southeast-2

# tags to add to the pipeline
tags:
  project: *projectName
  anything: else

stages:
  - stageName: testStage
    stacks:
      - stackName: testStack
        implementation: stacks.TestApplication.MyApplicationStack
        environment:
          account: '0123456789012'
          region: ap-southeast-2
        stackParameters:
          foo: bar
          whiz: bang
          thisThing:
            hello: world
            world: hello

  - stageName: prodStage
    stacks:
      - stackName: prodStack
        implementation: stacks.TestStackInjection.InjectionTestStack
        manualApproval: true
        environment:
          account: '0123456789012'
          region: ap-southeast-2
        stackParameters:
          foo: bar
          whiz: bang
          injectedStackParams:
            stackName: 'InjectedStack'
            environment:
              account: 'youraccount' # tests using the alias->id function
              region: 'ap-southeast-2'

      # - stackName: prodStackTwo
      #   implementation: stacks.ApplicationStack.MyApplicationStack
      #   manualApproval: false
      #   environment:
      #     account: '0123456789012'
      #     region: ap-southeast-2
      #   stackParameters:
      #     foo: bar
      #     whiz: bang
      #     thisThing:
      #       hello: world
      #       world: hello
